version: '2'
services:
  red-xcache-test:
    build: .
    volumes:
     - /etc/grid-security/red-xcache1-hostcert.pem:/etc/grid-security/hostcert.pem:ro
     - /etc/grid-security/red-xcache1-hostkey.pem:/etc/grid-security/hostkey.pem:ro
     - /etc/xrootd/cache-disks.config:/etc/xrootd/cache-disks.config:ro
     #- /cache:/cache
     - /etc/xrootd/macaroon-secret:/etc/xrootd/macaroon-secret:ro
    env_file: /root/red-xcache/envfile
    # Allow gdb inside
    privileged: true
    ports:
    - "10094:1094"

