version: '2'
services:
  red-xcache:
    build: .
    volumes:
     - /etc/grid-security/red-xcache1-hostcert.pem:/etc/grid-security/hostcert.pem:ro
     - /etc/grid-security/red-xcache1-hostkey.pem:/etc/grid-security/hostkey.pem:ro
     - /etc/xrootd/cache-disks.config:/etc/xrootd/cache-disks.config:ro
     - /cache:/cache
     - /etc/xrootd/macaroon-secret:/etc/xrootd/macaroon-secret:ro
    env_file: /root/red-xcache/envfile
    # Allow gdb inside
    privileged: true
    restart: unless-stopped
    # Switch to host-mode networking for now
    #ports:
    #- "1094:1094"
    network_mode: host

